apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: complex-k8s-com-tls
spec:
  secretName: complex-k8s-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chedcheatham.com
  dns:
    - chedcheatham.com
    - www.chedcheatham.com
  acme:
    config:
      - http01:
        ingressClass: nginx
        domains:
          - chedcheatham.com
          - www.chedcheatham.com
